export const teamMembers = [
  {
    id: 1,
    firstName: 'Екатерина',
    lastName: 'Сацура',
    role: 'Mentor',
    photo: '/aboutUs/satsura.jpg',
    github: 'ksatsura',
  },
  {
    id: 2,
    firstName: 'Андрей',
    lastName: 'Барышев',
    role: 'Team Lead',
    photo: '/aboutUs/baryshev.jpg',
    github: 'chebb44',
  },
  {
    id: 3,
    firstName: 'Вероника',
    lastName: 'Мартинович',
    role: 'Front-end developer',
    photo: '/aboutUs/martinovich.jpg',
    github: 'veronika-martinovich',
  },
  {
    id: 4,
    firstName: 'Владимир',
    lastName: 'Луговцов',
    role: 'Front-end developer',
    photo: '/aboutUs/lugovczov.jpg',
    github: 'lugovczov',
  },
  {
    id: 5,
    firstName: 'Игорь',
    lastName: 'Буренко',
    role: 'Front-end developer',
    photo: '/aboutUs/burenko.jpg',
    github: 'igorburenko',
  },
  {
    id: 6,
    firstName: 'Константин',
    lastName: 'Котов',
    role: 'Front-end developer',
    photo: '/aboutUs/kotov.jpg',
    github: 'Kostanios',
  },
];
