export const AUDIO_CALL_START_SCREEN = 'AUDIO_CALL_START_SCREEN';
export const AUDIO_CALL_STATISTIC_SCREEN = 'AUDIO_CALL_STATISTIC_SCREEN';
export const AUDIO_CALL_GAME_SCREEN = 'AUDIO_CALL_GAME_SCREEN';
export const AUDIO_CALL_END_SCREEN = 'AUDIO_CALL_END_SCREEN';

export const SHOW_TRUE = 'SHOW_TRUE';
export const MAX_WORDS_FOR_GAME = 10;
